#ifndef _ALTERA_MEMORYDMA_M_WRITE_H_
#define _ALTERA_MEMORYDMA_M_WRITE_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'MemoryDMA' and devices
 * connected to the following master:
 *   m_write
 * This master belong to master group 'MemoryDMA_m_write'
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for module 'MemoryDMA', class 'altera_avalon_sgdma'.
 * The macros have no prefix.
 */
#define ADDRESS_WIDTH 32
#define ALWAYS_DO_MAX_BURST 1
#define ATLANTIC_CHANNEL_DATA_WIDTH 4
#define AVALON_MM_BYTE_REORDER_MODE 0
#define BURST_DATA_WIDTH 8
#define BURST_TRANSFER 0
#define BYTES_TO_TRANSFER_DATA_WIDTH 16
#define CHAIN_WRITEBACK_DATA_WIDTH 32
#define COMMAND_FIFO_DATA_WIDTH 104
#define CONTROL_DATA_WIDTH 8
#define CONTROL_SLAVE_ADDRESS_WIDTH 4
#define CONTROL_SLAVE_DATA_WIDTH 32
#define DESCRIPTOR_READ_BURST 0
#define DESC_DATA_WIDTH 32
#define HAS_READ_BLOCK 0
#define HAS_WRITE_BLOCK 1
#define IN_ERROR_WIDTH 0
#define OUT_ERROR_WIDTH 0
#define READ_BLOCK_DATA_WIDTH 8
#define READ_BURSTCOUNT_WIDTH 4
#define STATUS_TOKEN_DATA_WIDTH 24
#define STREAM_DATA_WIDTH 8
#define SYMBOLS_PER_BEAT 1
#define UNALIGNED_TRANSFER 1
#define WRITE_BLOCK_DATA_WIDTH 8
#define WRITE_BURSTCOUNT_WIDTH 4

/*
 * Macros for device 'onchip', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_COMPONENT_NAME onchip
#define ONCHIP_BASE 0x80000
#define ONCHIP_SPAN 170000
#define ONCHIP_END 0xa980f
#define ONCHIP_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 1
#define ONCHIP_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_CONTENTS_INFO ""
#define ONCHIP_DUAL_PORT 0
#define ONCHIP_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_INIT_CONTENTS_FILE soc_system_onchip
#define ONCHIP_INIT_MEM_CONTENT 1
#define ONCHIP_INSTANCE_ID oc2
#define ONCHIP_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_RAM_BLOCK_TYPE AUTO
#define ONCHIP_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_SINGLE_CLOCK_OP 0
#define ONCHIP_SIZE_MULTIPLE 1
#define ONCHIP_SIZE_VALUE 170000
#define ONCHIP_WRITABLE 1
#define ONCHIP_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32
#define ONCHIP_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip


#endif /* _ALTERA_MEMORYDMA_M_WRITE_H_ */
