#ifndef _ALTERA_MSGDMA_0_H_
#define _ALTERA_MSGDMA_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'msgdma_0' and devices
 * connected to the following master:
 *   mm_write
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for module 'msgdma_0', class 'altera_msgdma'.
 * The macros have no prefix.
 */
#define BURST_ENABLE 0
#define BURST_WRAPPING_SUPPORT 0
#define CHANNEL_ENABLE 0
#define CHANNEL_ENABLE_DERIVED 0
#define CHANNEL_WIDTH 8
#define DATA_FIFO_DEPTH 64
#define DATA_WIDTH 8
#define DESCRIPTOR_FIFO_DEPTH 128
#define DMA_MODE 2
#define ENHANCED_FEATURES 0
#define ERROR_ENABLE 0
#define ERROR_ENABLE_DERIVED 0
#define ERROR_WIDTH 8
#define MAX_BURST_COUNT 2
#define MAX_BYTE 1024
#define MAX_STRIDE 1
#define PACKET_ENABLE 1
#define PACKET_ENABLE_DERIVED 1
#define PREFETCHER_ENABLE 0
#define PROGRAMMABLE_BURST_ENABLE 0
#define RESPONSE_PORT 2
#define STRIDE_ENABLE 0
#define STRIDE_ENABLE_DERIVED 0
#define TRANSFER_TYPE Unaligned Accesses

/*
 * Macros for device 'onchip', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_COMPONENT_NAME onchip
#define ONCHIP_BASE 0x80000
#define ONCHIP_SPAN 170000
#define ONCHIP_END 0xa980f
#define ONCHIP_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 1
#define ONCHIP_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_CONTENTS_INFO ""
#define ONCHIP_DUAL_PORT 0
#define ONCHIP_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_INIT_CONTENTS_FILE soc_system_onchip
#define ONCHIP_INIT_MEM_CONTENT 1
#define ONCHIP_INSTANCE_ID oc2
#define ONCHIP_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_RAM_BLOCK_TYPE AUTO
#define ONCHIP_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_SINGLE_CLOCK_OP 0
#define ONCHIP_SIZE_MULTIPLE 1
#define ONCHIP_SIZE_VALUE 170000
#define ONCHIP_WRITABLE 1
#define ONCHIP_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32
#define ONCHIP_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip


#endif /* _ALTERA_MSGDMA_0_H_ */
